const path = require('path')
console.log(path.dirname('E:/Yogesh1/Node Tutorial/pathModule/path.js'))
console.log(path.extname('E:/Yogesh1/Node Tutorial/pathModule/path.js'))
console.log(path.basename('E:/Yogesh1/Node Tutorial/pathModule/path.js'))
console.log(path.parse('E:/Yogesh1/Node Tutorial/pathModule/path.js'))